### ISSUE TITLE
Asynchronous Feedback

### ISSUE THREAD

**Issue by fsodari** [half-spin/hp_dac_proto_fw#12]
There will always be some slight mismatch in sampling frequency but I think the clocks should always be within 1Hz. If not, we need a better clock.

So we need to adjust the host sampling frequency on the fly. There are a few ways I've seen how to do this.

- Monitor the state of the buffer, if it's growing send less data, if it's shrinking send more. Kinda hacky, but it might work.

- Count sample clocks (in hw) between each SOF. Should give an exact number for what the sampling is, but SOF may have some jitter (I think.) so it needs to be averaged out and check for values out of range. With enough buffering, I think this is the way to go.

**Comment by fsodari** [comment]
I think this means dma needs to be stopped and reconfigured? Can it be reconfigured on the fly? Do we need two buffers and two DMA transfers to handle any gaps or memory misalignment?

**Comment by fsodari** [comment]
Did some tests with option 2. Counted the total number of (sample)clock cycles over 256 USB frames. Sample clock is 4.608Mhz so we should get an average of 4608 clocks per frame.

I let it run a few times, and stopped it (debugging) to check the counters.
Total clock edges: 1179355
Average (integer): 4606
Error = 0.04%

If we assume the USB SOF is God, then this means the local sample rate is 47.988kHz. This is a bit further off than I would like. Getting within +/- 1Hz would be kick ass. Perhaps Abies should get a oscillator instead of a crystal. Still need to figure out how to change the sample rate. It would be good to collect this data over a much longer period of time and see what it looks like.

It's usually that exact same value every time or pretty close, but once it was 
Total clock edges: 1183964
Average: 4624!
Error: 0.34% (atrocious!)

**Comment by jklein3** [comment]
@fsodari, if I'm understanding there's drift in the frequency of the SOF from USB, which is mismatching with the output clock frequency. If that's correct, I'd think we want to take output clock as God, not the SOF from USB, since I'd assume the crystal on the board is more precise than the USB SOF.

If all that's correct, could we just do a bunch of your testing to see what the max drift away from 4.608MHz the SOF is we see, and the max length of time that drift is seen and then set the buffer size such that it can handle at least that much of a drift for that period of time? So as non-zero data starts coming in, let the buffer fill to the correct fill line so that it could handle the SOF drift being lower than 4.608MHz for that period of time (plus some, maybe 2x?) before sending data off to the DAC. And have an equal size of headroom on the buffer to handle drift of the SOF above 4.608MHz for that period of time.

I suppose then we'd then necessarily be assuming there'd be on average over an extended period of time an equal drift in both directions such that the current buffer size always averages out to about that starting fill line.

**Comment by jklein3** [comment]
@fsodari or... What if we did a combination of the two somehow? If we can figure out how much increase/decrease in output frequency we can tolerate and not have a degradation in audio quality, and some how make sure the output frequency doesn't surpass that range by setting the buffer appropriately large enough to accommodate some drift in the SOF, but not as massive as it would be in my previous comment, then we're at least fixing it more efficiently.

**Comment by jklein3** [comment]
http://ww1.microchip.com/downloads/en/AppNotes/00002582A.pdf

Quote from above that might help:

> In an asynchronous endpoint implementation, the device addresses buffer overflow and underflow by
maintaining count or watermark levels for buffer overflow (upper level) and underflow (lower level)
conditions. When the device senses that the buffer count is exceeding the watermark levels, it sends a
message to the host to speed up or slow down. This message from the device to the host is called the
feedback message. The feedback message is transferred over a dedicated standard isochronous
synchronous endpoint, called the feedback endpoint. The explicit feedback from the device contains
information such as the amount, by which to speed up or slow down. The host speeds up or slows down
by adjusting its data rate corresponding to the feedback value received from the device.

**Comment by fsodari** [comment]
Good enough. I think it works, but there may be other problems.
